name: nf-core branch protection
# This workflow is triggered on PRs to master branch on the repository
# It fails when someone tries to make a PR against the nf-core `master` branch instead of `dev`
on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      
      # PRs are only ok if coming from an nf-core `dev` branch or a fork `patch` branch
      - name: Check PRs
        if: github.repository == 'nf-core/gwasgsa'
        run: |
          { [[ ${{github.event.pull_request.head.repo.full_name}} == nf-core/gwasgsa ]] && [[ $GITHUB_HEAD_REF = "dev" ]]; } || [[ $GITHUB_HEAD_REF == "patch" ]]
      - name: Check PRs in another repository
        if: github.repository == 'lifebit-ai/gwasgsa'
        run: |
          { [[ ${{github.event.pull_request.head.repo.full_name}} == lifebit-ai/gwasgsa ]] && [[ $GITHUB_HEAD_REF = "dev" ]]; } || [[ $GITHUB_HEAD_REF == "patch" ]]
